site_name: Wagtail Content Import Documentation
theme:
  name: 'material'
  favicon: 'img/wagtail_content_import_icon.svg'
  logo: 'img/wagtail_content_import_icon.svg'
  palette:
    primary: 'teal'
    accent: 'indigo'
markdown_extensions:
  - codehilite
nav:
    - Home: index.md
    - Getting Started:
      - Basic Setup: getting_started.md
      - Google Docs Setup: google_docs_setup.md
      - Microsoft Setup: microsoft_setup.md
    - Basic Usage: basic_usage.md
    - The Content Import Flow: flow.md
    - Customisation:
      - Writing Custom Converters: custom_converters.md
      - Working With StructBlocks: structblocks.md
      - Changing Import Fields: changing_import_fields.md
    - Settings Reference: settings.md
    - Submitting a New Backend: submitting_backend.md
